// src/app/layout.js
import "./globals.css";
import { AuthProvider } from "./components/AuthProvider";
import localFont from 'next/font/local';
import { Toaster } from "react-hot-toast";

const inter = localFont({
  src: [
    { path: './fonts/Inter-Thin.otf', weight: '100', style: 'normal' },
    { path: './fonts/Inter-Regular.otf', weight: '400', style: 'normal' },
    { path: './fonts/Inter-Medium.otf', weight: '500', style: 'normal' },
    { path: './fonts/Inter-SemiBold.otf', weight: '600', style: 'normal' },
    { path: './fonts/Inter-Bold.otf', weight: '700', style: 'normal' },
    { path: './fonts/Inter-Light.otf', weight: '700', style: 'normal' },

  ],
  variable: '--font-inter', // لاستخدامه في CSS variables إذا أردت
});
export const metadata = {
  title: "PackSpace", // هنا يكون اسم الموقع في جميع الصفحات
  description: "Generated by PackSpace",
  icons: {
    icon: "/LOGO.png", // ضع شعارك هنا في public/favicon.ico
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`overflow-x-hidden ${inter.className}`}>
    <head>
        <link rel="icon" href="/LOGO.png" />
        <title>PackSpace</title>
      </head>
      <body>
      
      <AuthProvider>
 
        {children}
        

        </AuthProvider>
        <Toaster position="top-center" />
        </body>
    </html>
  );
}
